services:
  mailpit:
    container_name: vansour-image-sqlite-mailpit
    image: axllent/mailpit:latest
    ports:
      - "18025:8025"
      - "11025:1025"
    healthcheck:
      test: wget --quiet --output-document=- http://localhost:8025/api/v1/info || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
